dist: trusty

language: cpp
compiler:
    - clang
    - gcc

install:
    - sudo apt-get -y -q update
    - sudo apt-get -y -q build-dep herbstluftwm
    - sudo apt-get -y -q install dzen2

script:
    - make -j2
    - sudo make PREFIX=/usr install
    - xvfb-run herbstluftwm &
    - sleep 1
    - DISPLAY=:99 herbstclient version

