dist: trusty

language: cpp
compiler:
    - clang
    - gcc

install:
    - sudo apt-get build-dep herbstluftwm

script:
    - make -j2
    - xvfb-run ./herbstluftwm &
    - sleep 1
    - ./herbstclient version
